### ISSUE TITLE
I tried to run the example code, but nothing happens after connecting to my buzz

### ISSUE THREAD

**Issue by version0chiro** [neosensory/neosensory-sdk-for-android-java#7]
I have tried the code and used version 1.0.1 from jitpack in my implementations, However, when trying to go beyond the connection phase of my buzz, nothing happens, The log cats do show that it is connected to my buzz but the other buttons and text view does not become visible, trying to force them only made the app crash. Here are my logs.
```

2020-12-28 17:13:45.377 9379-9379/? I/.neosensorytes: Late-enabling -Xcheck:jni
2020-12-28 17:13:45.437 9379-9379/? W/.neosensorytes: miui_dex2oat: DeoptimizeBootImage: patch entry points of methods in boot image to interpreter bridge
2020-12-28 17:13:45.587 9379-9379/com.example.neosensorytest W/.neosensorytes: miui_dex2oat: oat file of /data/app/com.example.neosensorytest-Iw2UkO_1c-UjNMqkgCE0IA==/base.apk is not exists
2020-12-28 17:13:45.684 9379-9379/com.example.neosensorytest W/.neosensorytes: miui_dex2oat: /data/app/com.example.neosensorytest-Iw2UkO_1c-UjNMqkgCE0IA==/base.apk: Fall back to running out of the original dex file.
2020-12-28 17:13:45.696 9379-9379/com.example.neosensorytest I/Perf: Connecting to perf service.
2020-12-28 17:13:45.783 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
2020-12-28 17:13:45.783 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
2020-12-28 17:13:45.783 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
2020-12-28 17:13:45.783 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
2020-12-28 17:13:45.783 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
2020-12-28 17:13:45.859 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden field Landroid/view/WindowInsets;->CONSUMED:Landroid/view/WindowInsets; (light greylist, reflection)
2020-12-28 17:13:45.878 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
2020-12-28 17:13:45.978 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2020-12-28 17:13:45.982 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2020-12-28 17:13:46.223 9379-9379/com.example.neosensorytest W/.neosensorytes: Accessing hidden method Landroid/graphics/Insets;->of(IIII)Landroid/graphics/Insets; (light greylist, linking)
2020-12-28 17:13:46.261 9379-9436/com.example.neosensorytest I/Adreno: QUALCOMM build                   : 89f10b9, I3d0e3ac366
    Build Date                       : 12/25/18
    OpenGL ES Shader Compiler Version: EV031.25.14.03
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2020-12-28 17:13:46.261 9379-9436/com.example.neosensorytest I/Adreno: Build Config                     : S P 6.0.9 AArch64
2020-12-28 17:13:46.264 9379-9436/com.example.neosensorytest I/Adreno: PFP: 0x016ee177, ME: 0x00000000
2020-12-28 17:13:46.270 9379-9436/com.example.neosensorytest I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2020-12-28 17:13:46.270 9379-9436/com.example.neosensorytest I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-12-28 17:13:46.270 9379-9436/com.example.neosensorytest I/OpenGLRenderer: Initialized EGL, version 1.4
2020-12-28 17:13:46.270 9379-9436/com.example.neosensorytest D/OpenGLRenderer: Swap behavior 2
2020-12-28 17:13:46.382 9379-9436/com.example.neosensorytest E/LB: fail to open file: No such file or directory
2020-12-28 17:13:47.915 9379-9379/com.example.neosensorytest D/BluetoothAdapter: isLeEnabled(): ON
2020-12-28 17:13:47.918 9379-9422/com.example.neosensorytest D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=11 mScannerId=0
2020-12-28 17:13:47.972 9379-9379/com.example.neosensorytest I/NeosensoryBlessed: Found peripheral 'BuzzD67BD76E5945'
2020-12-28 17:13:47.973 9379-9379/com.example.neosensorytest D/BluetoothAdapter: isLeEnabled(): ON
2020-12-28 17:13:48.084 9379-9379/com.example.neosensorytest D/BluetoothGatt: connect() - device: D6:7B:D7:6E:59:45, auto: false
2020-12-28 17:13:48.084 9379-9379/com.example.neosensorytest D/BluetoothGatt: registerApp()
2020-12-28 17:13:48.084 9379-9379/com.example.neosensorytest D/BluetoothGatt: registerApp() - UUID=622ccf59-74cd-48f9-abd2-84d54bca77a3
2020-12-28 17:13:48.088 9379-9422/com.example.neosensorytest D/BluetoothGatt: onClientRegistered() - status=0 clientIf=11
2020-12-28 17:13:48.971 9379-9422/com.example.neosensorytest D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=11 device=D6:7B:D7:6E:59:45
2020-12-28 17:13:48.992 9379-9379/com.example.neosensorytest D/BluetoothGatt: discoverServices() - device: D6:7B:D7:6E:59:45
2020-12-28 17:13:49.004 9379-9422/com.example.neosensorytest D/BluetoothGatt: onSearchComplete() = Device=D6:7B:D7:6E:59:45 Status=0
2020-12-28 17:13:49.009 9379-9379/com.example.neosensorytest I/NeosensoryBlessed: connected to 'BuzzD67BD76E5945'
2020-12-28 17:13:49.013 9379-9379/com.example.neosensorytest I/NeosensoryBlessed: SUCCESS: CLI ready to accept commands
2020-12-28 17:13:49.013 9379-9379/com.example.neosensorytest D/BluetoothGatt: setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
2020-12-28 17:13:53.717 9379-9427/com.example.neosensorytest I/.neosensorytes: ProcessProfilingInfo new_methods=1544 is saved saved_to_disk=1 resolve_classes_delay=8000
2020-12-28 17:14:18.963 9379-9422/com.example.neosensorytest D/BluetoothGatt: onClientConnectionState() - status=22 clientIf=11 device=D6:7B:D7:6E:59:45
2020-12-28 17:14:18.966 9379-9422/com.example.neosensorytest D/BluetoothGatt: close()
2020-12-28 17:14:18.967 9379-9422/com.example.neosensorytest D/BluetoothGatt: unregisterApp() - mClientIf=11

```

**Comment by version0chiro** [comment]
The error that appears when trying to hard visible the buttons and send vibrations 
```
2020-12-28 18:46:00.660 28632-28632/com.example.neosensorytest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.neosensorytest, PID: 28632
    java.lang.NoSuchMethodError: No virtual method writeCharacteristic(Landroid/bluetooth/BluetoothGattCharacteristic;[BI)Z in class Lcom/welie/blessed/BluetoothPeripheral; or its super classes (declaration of 'com.welie.blessed.BluetoothPeripheral' appears in base.apk)
        at com.neosensory.neosensoryblessed.NeosensoryBlessed.sendCommand(NeosensoryBlessed.java:96)
        at com.neosensory.neosensoryblessed.NeosensoryBlessed.stopAudio(NeosensoryBlessed.java:169)
        at com.neosensory.neosensoryblessed.NeosensoryBlessed.pauseDeviceAlgorithm(NeosensoryBlessed.java:111)
        at com.example.neosensorytest.MainActivity$2.onClick(MainActivity.java:197)
        at android.view.View.performClick(View.java:6612)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:6589)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25925)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```

**Comment by GreatScott** [comment]
Hi! 

It looks like BLESSED had a new release 2 days ago, which breaks compatibility. I made the unwise decision of using the master branch release in our library, which in turn causes our project to crash. We're working on a fix now. Should have something in the next day or so.

In the meantime, you can try to use the neosensoryblessed project in this repo (instead of going through jitpack) and replace the blessed version from `'com.github.weliem:blessed-android:master-SNAPSHOT'` ->` 'com.github.weliem:blessed-android:1.30'` in the neosensoryblessed build.gradle file, i.e.

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    **implementation 'com.github.weliem:blessed-android:1.30'**
}
```

Let us know if that doesn't work!

**Comment by GreatScott** [comment]
Hi @version0chiro -- just added a new build (v1.1.2) that hopefully fixes your issue. Can you please try that and report back? Also what version of Android + device are you running?

**Comment by version0chiro** [comment]
Hey @GreatScott , thanks for the quick response, yes after updating to v1.1.2 I have been able to run the app and vibrate the buzz from the buttons on command. I have tested the app on two different android devices, one with android 9 and one with android 10 both giving proper results.
